### ISSUE TITLE
The URL for the Code of Conduct is incorrect

### ISSUE THREAD

**Issue by openbrian** [18F/chat#14]
When going to https://chat.18f.gov/ and filling out the form, I see this link to read the Code of Conduct.

I have read and agree to abide by 18F's Code of Conduct. *
https://github.com/18F/code-of-conduct/blob/master/code-of-conduct.md#readme
[ ] Agree

This link appears to be incorrect as it leads to a 404.

Maybe you need to use the githubusercontent type of URL.  Shrug.

**Comment by afeld** [comment]
Sorry, that URL is now live again. Thanks!
