### ISSUE TITLE
Outage?

### ISSUE THREAD

**Issue by NoahKunin** [18F/chat#9]
I searched Slack iutself, but didn't see any notice on what happened to chat.18f.gov. Can anyone document this outage?

cc @afeld @konklone

**Comment by afeld** [comment]
It's because of the Slack integrations being disabled.

/cc https://github.com/18F/chat/pull/8

**Comment by NoahKunin** [comment]
Ok - I thought it was down beforehand, but maybe I've lost track of linear time. Closing!

**Comment by afeld** [comment]
Still relevant/accurate!

**Comment by pburkholder** [comment]
@afeld @NoahKunin This repo is among the top links for Google search on '18f join public slack', which then leads to trying, https://chat.18f.gov/devops-public (and the resulting `404 Not Found: Requested route ('chat.18f.gov') does not exist.`)

If public chat has gone away, then perhaps we can update the  README to note that, or suggest an alternate means of joining if the integration is unsupported. 

Anyhow, to the point, I'd be interested in joining opensource-public and devops-public.

Thanks, Peter

**Comment by afeld** [comment]
We hope to have it resolved soon. Thanks for your patience!

**Comment by pburkholder** [comment]
Would y'all be able to add manually pending the revival of this?

**Comment by afeld** [comment]
We are now back up.
